CREATE TABLE NIVEL_PERMISSAO(
	[Nivel] INTEGER PRIMARY KEY
);

CREATE TABLE UTILIZADOR(
	[Id] INTEGER PRIMARY KEY
	[Nome] VARCHAR(256) NOT NULL,
	[Password] VARCHAR(256) NOT NULL,
	[Telefone] INTEGER NOT NULL,
	[DataNascimento] DATE NOT NULL,
	[NivelPermissao_Nivel] INTEGER REFERENCES NIVEL_PERMISSAO(Nivel) NOT NULL
);

CREATE TABLE HORARIO_MONITORIZACAO(
	[Id] INTEGER PRIMARY KEY,
	[HoraInicio] DATE,
	[HoraFim] DATE,
	[Estado] BIT NOT NULL,
);

CREATE TABLE AREA_RESTRITA(
	[Id] INTEGER PRIMARY KEY,
	[DESCRICAO] VARCHAR(512),
	[LOCALIZACAO] VARCHAR(512)
);

CREATE TABLE AREA_RESTRITA_HORARIO_MONITORIZACAO(
	[AreaRestrita_Id] INTEGER REFERENCES AREA_RESTRITA(Id),
	[HorarioMonitorizacao_Id] INTEGER REFERENCES HORARIO_MONITORIZACAO(Id),
	PRIMARY KEY (AreaRestrita_Id, HorarioMonitorizacao_Id)
);

CREATE TABLE AREA_RESTRITA_CONTACTA_UTILIZADOR(
	[AreaRestrita_Id] INTEGER REFERENCES AREA_RESTRITA(Id),
	[Utilizador_Id] INTEGER REFERENCES UTILIZADOR(Id),
	[HoraInicio] DATE NOT NULL,
	[HoraFim] DATE NOT NULL,
	PRIMARY KEY (AreaRestrita_Id, Utilizador_Id)
);

CREATE TABLE AREA_RESTRITA_PERTENCE_UTILIZADOR(
	[AreaRestrita_Id] INTEGER REFERENCES AREA_RESTRITA(Id),
	[Utilizador_Id] INTEGER REFERENCES UTILIZADOR(Id),
	PRIMARY KEY (AreaRestrita_Id, Utilizador_Id)
);

CREATE TABLE HORARIO_EXCLUSAO(
	[Id] INTEGER PRIMARY KEY,
	[DataInicio] DATE NOT NULL,
	[DataFim] DATE NOT NULL
);

CREATE TABLE AREA_RESTRITA_HORARIO_EXCLUSAO(
	[AreaRestrita_Id] INTEGER REFERENCES AREA_RESTRITA(Id),
	[HorarioExclusao_Id] INTEGER REFERENCES HORARIO_EXCLUSAO(Id),
	PRIMARY KEY (AreaRestrita_Id, HorarioExclusao_Id)
);

CREATE TABLE ESTADO_MANUTENCAO(
	[Descricao] VARCHAR(64) PRIMARY KEY
);

CREATE TABLE MANUTENCOES()
