USE WasteNot_Warning;
GO

DELETE FROM UTILIZADOR_REGISTO_EVENTOS;
DELETE FROM REGISTO_EVENTOS;
DELETE FROM TIPO_EVENTO;
DELETE FROM DISPOSITIVO_ACESSO;
DELETE FROM DISPOSITIVO_SEGURANCA;
DELETE FROM TIPO_DISPOSITIVO_SEGURANCA;
DELETE FROM DISPOSITIVO;
DELETE FROM MANUTENCOES;
DELETE FROM ESTADO_MANUTENCAO;
DELETE FROM AREA_RESTRITA_HORARIO_EXCLUSAO;
DELETE FROM HORARIO_EXCLUSAO;
DELETE FROM AREA_RESTRITA_PERTENCE_UTILIZADOR;
DELETE FROM AREA_RESTRITA_CONTACTA_UTILIZADOR;
DELETE FROM AREA_RESTRITA_HORARIO_MONITORIZACAO;
DELETE FROM AREA_RESTRITA;
DELETE FROM HORARIO_MONITORIZACAO;
DELETE FROM UTILIZADOR;
DELETE FROM NIVEL_PERMISSAO;

/*
ALTER TABLE UTILIZADOR
ADD [PW_Hash] VARBINARY(32) NOT NULL,
    [Salt] VARBINARY(16) NOT NULL;
SELECT * FROM UTILIZADOR;
*/