USE p1g6;
GO

--Delete data
DELETE FROM UTILIZADOR_REGISTO_EVENTOS;
DELETE FROM REGISTO_EVENTOS;
DELETE FROM TIPO_EVENTO;
DELETE FROM DISPOSITIVO_ACESSO;
DELETE FROM DISPOSITIVO_SEGURANCA;
DELETE FROM TIPO_DISPOSITIVO_SEGURANCA;
DELETE FROM DISPOSITIVO;
DELETE FROM MANUTENCOES;
DELETE FROM ESTADO_MANUTENCAO;
DELETE FROM AREA_RESTRITA_HORARIO_EXCLUSAO;
DELETE FROM HORARIO_EXCLUSAO;
DELETE FROM AREA_RESTRITA_PERTENCE_UTILIZADOR;
DELETE FROM AREA_RESTRITA_CONTACTA_UTILIZADOR;
DELETE FROM AREA_RESTRITA_HORARIO_MONITORIZACAO;
DELETE FROM AREA_RESTRITA;
DELETE FROM HORARIO_MONITORIZACAO;
DELETE FROM UTILIZADOR;
DELETE FROM NIVEL_PERMISSAO;
GO

-- Delete tables
DROP TABLE IF EXISTS UTILIZADOR_REGISTO_EVENTOS;
DROP TABLE IF EXISTS REGISTO_EVENTOS;
DROP TABLE IF EXISTS TIPO_EVENTO;
DROP TABLE IF EXISTS DISPOSITIVO_ACESSO;
DROP TABLE IF EXISTS DISPOSITIVO_SEGURANCA;
DROP TABLE IF EXISTS TIPO_DISPOSITIVO_SEGURANCA;
DROP TABLE IF EXISTS DISPOSITIVO;
DROP TABLE IF EXISTS MANUTENCOES;
DROP TABLE IF EXISTS ESTADO_MANUTENCAO;
DROP TABLE IF EXISTS AREA_RESTRITA_HORARIO_EXCLUSAO;
DROP TABLE IF EXISTS HORARIO_EXCLUSAO;
DROP TABLE IF EXISTS AREA_RESTRITA_PERTENCE_UTILIZADOR;
DROP TABLE IF EXISTS AREA_RESTRITA_CONTACTA_UTILIZADOR;
DROP TABLE IF EXISTS AREA_RESTRITA_HORARIO_MONITORIZACAO;
DROP TABLE IF EXISTS AREA_RESTRITA;
DROP TABLE IF EXISTS HORARIO_MONITORIZACAO;
DROP TABLE IF EXISTS UTILIZADOR;
DROP TABLE IF EXISTS NIVEL_PERMISSAO;

--Delete Triggers
DROP TRIGGER IF EXISTS trg_CreateDispositivoSeguranca;
DROP TRIGGER IF EXISTS trg_CheckDateValidity;

-- Delete Stored Procedures
DROP PROCEDURE IF EXISTS GetRowCountOfEventsInExclusionTime;
DROP PROCEDURE IF EXISTS GetRowCountOfEventsInRepairingSchedule;
DROP PROCEDURE IF EXISTS GetRowCountOfEventsInActiveSchedule;
DROP PROCEDURE IF EXISTS getAlarmActivated;
DROP PROCEDURE IF EXISTS AddUserEvent;

-- Delete UDFs
DROP FUNCTION IF EXISTS dbo.GetLastUserEvents;
DROP FUNCTION IF EXISTS dbo.GetAreasRestritasByUserId;
DROP FUNCTION IF EXISTS dbo.GetLastRepairsOfARestrictedArea;
DROP FUNCTION IF EXISTS dbo.GetDeviceListOfARestrictedArea;
DROP FUNCTION IF EXISTS dbo.GetHorariosMonitorizacaoByRestrictedArea;
DROP FUNCTION IF EXISTS dbo.PaginatedEvents;

-- Delete Views
DROP VIEW IF EXISTS events_count_by_category;
DROP VIEW IF EXISTS next_repairs;
DROP VIEW IF EXISTS list_ordered_events;
DROP VIEW IF EXISTS events_count_by_category;
DROP VIEW IF EXISTS next_repairs;
DROP VIEW IF EXISTS list_ordered_events;