version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
    ports:
      - "8080:8080"
    volumes:
      - ./front/src:/front/src
    command: npm run dev --watch -- --host 0.0.0.0 --port 8080
            

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
    ports:
      - "5000:5000"
    volumes:
      - ./back/src:/back/src
    depends_on:
      - sql-server

    command: "flask --app App.py run --host=0.0.0.0"


  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword
    volumes:
      - ./db_data:/var/opt/mssql

