version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
    ports:
      - "8080:8080"
    volumes:
      - ./front/src:/front/src
    command: npm run dev --watch -- --host 0.0.0.0 --port 8080
    networks:
      my_network:
        ipv4_address: 172.16.0.2

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-prod}
      - DB_RESET_FLAG=${DB_RESET_FLAG:-false}
    ports:
      - "5000:5000"
    volumes:
      - ./back:/python-docker
      - ./database:/database

    command: sh -c "if [ \"$DB_RESET_FLAG\" = \"true\" ]; then python reset.py; fi && flask --app App.py run --host=0.0.0.0 --port 5000 --reload"
    networks:
      my_network:
        ipv4_address: 172.16.0.3



networks:
  my_network:
    ipam:
      config:
        - subnet: 172.16.0.0/24